config/routes.rb
Rails.application.routes.draw do
  devise_for :pirates

  resource :profile, only: [ :show, :edit, :update, :destroy]
  resources :pirates, only: :show
  resources :abordages, only: [:index]

  root to: 'tresors#index'

  get "crews/decouvrir", to: "crews#decouvrir"
  resources :crews do
    resources :crew_pirates, only:[:new, :create, :destroy]
    get "pirates", to: "crews#pirates"
  end

  resources :tresors do
    resources :abordages, only: [:create, :update]
    resources :crew_tresors, only:[:new, :create, :destroy]
  end

  get "pourparlers/traques", to: "abordages#traques"
  get "pourparlers/propositions", to: "abordages#propositions"
end

app/models/crew.rb
class Crew < ApplicationRecord
  has_many :crew_pirates
  has_many :crew_tresors
  has_many :pirates, through: :crew_pirates
  has_many :tresors, through: :crew_tresors

  validates :nom, presence: true, uniqueness: true

  # STATUSES = ["Public", "Privé"]
  # validates :status, inclusion: {in: STATUSES}

  def nice_nom
    "##{nom}"
  end

end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
# CRUD
  before_action :set_crew, only: [:show, :edit]
  skip_after_action :verify_authorized, only: [:decouvrir]
  after_action :verify_policy_scoped, only: [:decouvrir]

  def index
    @crew_list = policy_scope(current_pirate.crews).order(created_at: :desc)
  end

  def decouvrir
    @crew_list = Crew.all
    if params[:query]
      @crews = policy_scope(Crew).where("nom ILIKE ?", "%#{params[:query]}%").order(created_at: :desc)
    else
      @crews = policy_scope(Crew).order(created_at: :desc)
    end
  end

  def show
    authorize @crew
  end

  def pirates
    @crew = Crew.find(params[:crew_id])
    @pirates = @crew.pirates
    authorize @crew
  end

  def new
    @crew = Crew.new
    authorize @crew
  end

  def create
    @crew = Crew.new(crew_params)
    @crew.pirates.push(current_pirate)
    @crewpirate = CrewPirate.new(pirate_id: current_pirate.id, crew_id: @crew.id )
    authorize @crew
    if @crew.save
      @crewpirate = CrewPirate.create(pirate_id: current_pirate.id, crew_id: @crew.id)
      redirect_to crew_path(@crew)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @crew.update(crew_params)
    authorize @crew
    redirect_to crew_path(@crew)
  end

  def destroy
    @crew.destroy
    redirect_to crews_path
  end

  private
  def crew_params
    params.require(:crew).permit(:nom, :prive, :password)
  end

  def set_crew
    @crew = Crew.find(params[:id])
    # authorize @crew
  end
end

app/views/crews/_crew_list.html.erb
<% crews.each do |crew| %>
  <%= link_to crew_path(crew), class: 'no-text-decoration' do %>
  <div class="card-crew">
    <h2 class="h2-crew-card"><%= crew.nice_nom %>
      <% if crew.prive %>
      <%= image_tag "ferme.svg", height: 20, width: 20, crop: :fill%>
      <% end %>
    </h2>
    <div class="crew-compteurs">
      <p><%= pluralize crew.pirates.count, "pirate" %></p>
      <p><%= pluralize crew.tresors.count, "trésor" %></p>
    </div>
  </div>
  <% end %>
<% end %>

app/views/crews/_form.html.erb
<div class="container-tresor">
  <% content_for :meta_title, "Le Crew #{@crew.nom} a rejoint Gold Next Door" %>
  <% content_for :meta_description, "Le nouveau crew de Gold Next Door fait beaucoup parler de lui sur les internets" %>
  <% content_for :meta_image, image_path('Gold_Next_Door.png') %>

  <%= simple_form_for @crew do |f| %>
    <div class="form-inputs">
      <h2 class="h2-form-create-crew"> Quel nom pour ton Crew ?</h2>
      <%= f.input :nom, placeholder: "Le Gang du 16ème...", label: false %>

      <!-- creer ou non un crew -->
      <div class="container-checkbox">
        <div class="form-group radio_buttons optional crew_prive">
          <h2 class="h2-n2-form-create-crew"> Crew privé ou Crew public ?</h2>
          </label>

          <div id="crew_prive">
            <input type="hidden" name="crew[prive]" value="">
            <span class="radio">
              <label for="crew_prive_true">
                <input class="radio_buttons optional" type="radio" value="true" name="crew[prive]" id="crew_prive_true"><%= image_tag "ferme.svg", height: 80, width: 80, crop: :fill%>
              </label>
            </span>
            <span class="radio">
              <label for="crew_prive_false">
                <input class="radio_buttons optional" readonly="readonly" type="radio" value="false" name="crew[prive]" id="crew_prive_false"><%= image_tag "ouvert.svg", height: 80, width: 80, crop: :fill%>
              </label>
            </span>
            <!-- <p class="help-block text-center"><em>Les Crews privados n'apparaissent que sur invitation privée</em></p> -->
          </div>
        </div>
      </div>

      <!-- mdp -->
      <div class="form-group password required crew_password hidden" id="password_indice">
        <label class="control-label password required" for="password">
          <abbr title="required">*</abbr> Mot de passe de ton Crew</label>
          <input class="form-control password required" id="password" type="password" name="crew[password]">
        </div>

      <div class="wide_buttons">
        <%= f.button :submit, "En avant toute 💣", class: 'button yellow' %>
      </div>
    </div>
  <% end %>
</div>

app/views/crews/_header.html.erb
<div class="crew-header">
  <% if crew.pirates.exists?(current_pirate.id) %>
      <div class="mini_buttons">
      <%= link_to "Quitter X", crew_crew_pirate_path(crew, current_pirate), method: :delete, class: 'button' %>
    </div>
  <% end %>
  <h1 <%= "class= crew-prive-name" if crew.prive %> ><%= crew.nice_nom %></h1>
    <% if !crew.pirates.exists?(current_pirate.id) %>
      <div class="wide_buttons">
        <% if @crew.prive %>
        <!-- cas ou le crew est prive -->
        <%= link_to "Rejoindre ce Crew 😎", new_crew_crew_pirate_path(crew), class: 'button yellow' %>
        <% else %>
        <!-- cas ou le crew est public -->
        <%= link_to "Rejoindre ce Crew 😎", crew_crew_pirates_path(crew, crew_pirate), class: 'button yellow', method: :post %>
        <% end %>
      </div>
    <% end %>
</div>

app/views/crews/_list.html.erb
<% Crew.all.each do |crew| %>

<% end %>

app/views/crews/_nav.html.erb
<div class="tabs">
  <div class="tab-item <%= 'active' if tab == 1 %>">
    <%= link_to crew_path(crew) do %>
    <h3><%= pluralize crew.tresors.count, "Trésor" %></h3>
    <% end %>
  </div>
  <div class="tab-item <%= 'active' if tab == 2 %>">
    <%= link_to crew_pirates_path(crew) do %>
    <h3><%= pluralize crew.pirates.count, "Pirate" %></h3>
    <% end %>
  </div>
</div>

app/views/crews/_nav_index.html.erb
<div class="tabs">
  <div class="tab-item <%= 'active' if tab == 1 %>">
    <%= link_to crews_path do %>
    <h3>Mes Crews</h3>
    <% end %>
  </div>
  <div class="tab-item <%= 'active' if tab == 2 %>">
    <%= link_to crews_decouvrir_path do %>
    <h3>Découvrir</h3>
    <% end %>
  </div>
</div>

app/views/crews/decouvrir.html.erb
<%= render "crews/nav_index", tab: 2 %>
<div class="search-crew-global">
    <%= simple_form_for crews_path, method: :get, html: {id: "submittag"} do |f| %>
      <div class="search-crew">
        <%= select_tag :query, options_from_collection_for_select(@crew_list, :nom, :nom), class: 'select2' %>
      </div>
      <div class="search-submit">
        <%= f.submit :chercher, class: 'button yellow hidden'%>
      </div>
    <% end %>
  </div>
 <div class="container-tresor">
<%= render "crews/crew_list", crews: @crews %>
</div>

app/views/crews/index.html.erb
<% content_for :meta_title, "Tous les Crews de Gold Next Door" %>
<% content_for :meta_description, "Découvre tous les Crews présents sur Gold Next Door. Rejoins tes favoris !" %>
<% content_for :meta_image, image_path('Gold_Next_Door.png') %>

<%= render "crews/nav_index", tab: 1 %>
<div class="wide_buttons">
  <%= link_to "Crée un Crew ⚓", new_crew_path, class: 'button yellow' %>
</div>
<% if @crew_list.empty? %>
  <div class="crew-global-notif">
    <p>T'es dans aucun Crew pirate !</p>
    <div class="wide_buttons">
      <%= link_to "Adopte un crew", crews_decouvrir_path, class: 'button yellow' %>
    </div>
  </div>
<% else %>
  <%= render "crews/crew_list", crews: @crew_list %>
<% end %>

app/views/crews/new.html.erb
<% content_for :meta_title, "Un nouveau crew sur Gold Next Door !" %>
  <% content_for :meta_description, "Le nouveau crew de Gold Next Door fait beaucoup parler de lui sur les internets" %>
  <% content_for :meta_image, image_path('Gold_Next_Door.png') %>
<%= render 'form' %>

app/views/crews/pirates.html.erb
<% content_for :meta_title, "Le Crew #{@crew.nom} sur Gold Next Door" %>
<% content_for :meta_description, "Bienvenue matelot ! Envie de rejoindre cet équipage ?" %>
<% content_for :meta_image, image_path('Gold_Next_Door.png') %>

<%= render "crews/header", crew: @crew, crew_pirate: @crew_pirate %>

<% if @crew.pirates.exists?(current_pirate.id) || !@crew.prive %>
  <%= render "crews/nav", tab: 2, crew: @crew %>
  <% @crew.pirates.each do |pirate| %>
    <p class="crew-pirate"><% if pirate.photo? %>
      <%= cl_image_tag pirate.photo, class: 'avatar' %>
    <% else %>
      <%= image_tag 'pirate.svg', class: 'avatar' %>
    <% end %>
      <%= pirate.nice_pseudo %> <span class="tresors-per-pirate"><%= pluralize pirate.tresors.count, "trésor" %></span>
    </p>
  <% end %>
<% else %>
  <p class="crew-global-notif notif-closed-emoji">Ce crew est privé</p>
<% end %>

app/views/crews/show.html.erb
<% content_for :meta_title, "Rejoins le Crew #{@crew.nom} sur Gold Next Door" %>
<% content_for :meta_description, "Bienvenue matelot ! Envie de rejoindre cet équipage ?" %>
<% content_for :meta_image, image_path('Gold_Next_Door.png') %>

<%= render "crews/header", crew: @crew, crew_pirate: @crew_pirate %>
<% if @crew.pirates.exists?(current_pirate.id) || !@crew.prive %>
  <%= render "crews/nav", tab: 1, crew: @crew %>
  <%= render "tresors/list", tresors: @crew.tresors.order(created_at: :desc) %>
<% else %>
  <p class="crew-global-notif notif-closed-emoji">Ce crew est privé</p>
<% end %>