config/routes.rb
Rails.application.routes.draw do
  devise_for :pirates

  resource :profile, only: [ :show, :edit, :update, :destroy]
  resources :pirates, only: :show
  resources :abordages, only: [:index]

  root to: 'tresors#index'

  get "crews/decouvrir", to: "crews#decouvrir"
  resources :crews do
    resources :crew_pirates, only:[:new, :create, :destroy]
    get "pirates", to: "crews#pirates"
  end

  resources :tresors do
    resources :abordages, only: [:create, :update]
    resources :crew_tresors, only:[:new, :create, :destroy]
  end

  get "pourparlers/traques", to: "abordages#traques"
  get "pourparlers/propositions", to: "abordages#propositions"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
skip_after_action :verify_authorized

  def show
    @pirate = current_pirate
  end

  def edit
    @pirate = current_pirate
  end

  def update
    @pirate = current_pirate
    @pirate.update(pirate_params)
    redirect_to profile_path
  end

  def destroy
    @pirate = current_pirate
    @pirate.destroy
    redirect_to tresors_path
  end

  private
  def pirate_params
    params.require(:pirate).permit(:pseudo, :email, :photo)
  end
end

app/views/profiles/_form.html.erb
<div class="container-tresor">
  <%= simple_form_for @pirate, url: profile_path do |f| %>

    <!-- Upload picture -->
    <div class="photo-container">

      <%= f.label :photo do %>
        <%= image_tag 'profile_pic.svg', height: 70, width: 70 %>
      <% end %>
      <%= f.input :photo, label: false %>
      <%= f.input :photo_cache, as: :hidden%>
    </div>
    <%= f.input :email, label: "Modifier mon email :" %>
    <%= f.input :pseudo, label: 'Modifier mon pseudo :' %>

    <div class="wide_buttons">
      <%= f.submit "A l'abordage !", class: 'button yellow' %>
    </div>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/new.html.erb
<%= render 'form' %>

app/views/profiles/show.html.erb
<div class="container-tresor">
  <div class="container-profile">
    <% if pirate_signed_in? && @current_pirate.photo? %>
        <%= cl_image_tag @current_pirate.photo, class: 'avatar', height: 120, width: 120, crop: :fill, class: "avatar-profile" %>
      <% else %>
        <%= image_tag 'pirate.svg', class: 'avatar', height: 120, width: 120, crop: :fill, class: "avatar-profile" %>
    <% end %>
    <div class="flexbox-profil-updated">
      <div class="profil-pseudo">
        <h2><%= @pirate.nice_pseudo %></h2>
        <p><%= @pirate.email %></p>
      </div>
    </div>

    <div class=“crew-profile”>
      <h2 class="h2-profil-pirate">Mes Crews</h2>
      <ul id="sans-ul">
        <% @pirate.crews.each do |crew| %>
        <p class="break-word"><%= link_to crew.nice_nom, crew_path(crew) %></p>
        <% end %>
      </ul>
      <div class="wide_buttons">
      <button class="button yellow" id="modify">Modifier mon profil</button>
      </div>
      <div class="hidden" id="torender">
        <%= render "form" %>
        <hr>
      </div>
      <hr>
      <hr>
      <hr>
    </div>

  </div>
</div>