config/routes.rb
Rails.application.routes.draw do
  devise_for :pirates

  resource :profile, only: [ :show, :edit, :update, :destroy]
  resources :pirates, only: :show
  resources :abordages, only: [:index]

  root to: 'tresors#index'

  get "crews/decouvrir", to: "crews#decouvrir"
  resources :crews do
    resources :crew_pirates, only:[:new, :create, :destroy]
    get "pirates", to: "crews#pirates"
  end

  resources :tresors do
    resources :abordages, only: [:create, :update]
    resources :crew_tresors, only:[:new, :create, :destroy]
  end

  get "pourparlers/traques", to: "abordages#traques"
  get "pourparlers/propositions", to: "abordages#propositions"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer text-inline">
  <div>
    <%= link_to tresors_path, class: "decouvrir"  do %>
    <%= image_tag "telescope2.png", class: 'margin-footer', height: 40 %>
    <p class="footer-text">Traquer</p>
    <% end %>
  </div>
  <div>
    <%= link_to new_tresor_path, class: "tresor"  do %>
    <%= image_tag "bouton-principal5.png", id: 'tresor', class: 'margin-footer btn-principal', height: 110 %>
    <% end %>
  </div>
  <div>
    <%= link_to pourparlers_traques_path, class: "pourparlers"  do %>
    <%= image_tag "sword2.png", class: 'margin-footer', height: 40 %>
    <p class="footer-text">Pourparlers</p>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div>
  <%= link_to crews_path, class: "navbar-crew" do %>
    <%= image_tag "treasure-map.svg", height: 42 %>
    <p class="crew-navbar">#Crews</p>
  <% end %>
  </div>

  <div>
  <%= link_to tresors_path  do %>
  <%= image_tag "logo-gnd.png", class: "navbar-logo" %>
  <% end %>
  </div>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if pirate_signed_in? %>
      <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
        </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_pirate_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item">
    <div class="dropdown">

      <% if pirate_signed_in? && @current_pirate.photo? %>
        <%= cl_image_tag @current_pirate.photo, class: 'avatar', height: 50, data: { toggle: "dropdown" } %>
      <% else %>
        <%= image_tag 'pirate.svg', class: 'avatar', height: 50, data: { toggle: "dropdown" } %>
      <% end %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if pirate_signed_in? %>
      <%= cl_image_tag @current_pirate.photo, class: 'avatar', height: 50, data: { toggle: "dropdown" } %>
          <%= link_to destroy_pirate_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        <% else %>
          <li>
            <%= link_to t(".sign_in", default: "Login"), new_pirate_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
        <% end %>
        <%= link_to 'Profile', profile_path, class: "navbar-wagon-item navbar-wagon-link"  %>
      </ul>
    </div>
  </div>
</div>