config/routes.rb
Rails.application.routes.draw do
  devise_for :pirates

  resource :profile, only: [ :show, :edit, :update, :destroy]
  resources :pirates, only: :show
  resources :abordages, only: [:index]

  root to: 'tresors#index'

  get "crews/decouvrir", to: "crews#decouvrir"
  resources :crews do
    resources :crew_pirates, only:[:new, :create, :destroy]
    get "pirates", to: "crews#pirates"
  end

  resources :tresors do
    resources :abordages, only: [:create, :update]
    resources :crew_tresors, only:[:new, :create, :destroy]
  end

  get "pourparlers/traques", to: "abordages#traques"
  get "pourparlers/propositions", to: "abordages#propositions"
end

app/models/abordage.rb
class Abordage < ApplicationRecord
  belongs_to :tresor
  belongs_to :pirate
  belongs_to :type_abordage, optional: true

  validates_presence_of :tresor
  validates_presence_of :pirate
  validates_presence_of :message, if: :abordage_is_troll?
  validates_presence_of :quantite, scope: :type_abordage, unless: :abordage_is_troll?


  private

  def abordage_is_troll?
    quantite.nil? || type_abordage.nil?
  end
end

app/controllers/abordages_controller.rb
class AbordagesController < ApplicationController
  before_action :set_abordage, only: [:update]
  skip_after_action :verify_authorized, only: [:traques, :propositions]
  after_action :verify_policy_scoped, only: [:traques, :propositions]

  def traques
    @abordages = policy_scope(current_pirate.abordages.where.not(type_abordage: nil))
    @tresors = policy_scope(current_pirate.tresors)
  end

  def propositions
    @abordages = policy_scope(current_pirate.abordages.where.not(type_abordage: nil))
    @tresors = policy_scope(current_pirate.tresors).order(created_at: :desc)
  end


  def new
    authorize @abordage
  end

  def create
    @abordage = Abordage.new(abordage_params)
    @abordage.pirate = current_pirate
    @abordage.tresor = Tresor.find(params[:tresor_id])
    @tresor = @abordage.tresor
    authorize @abordage
    if @abordage.save
      respond_to do |format|
        format.html { redirect_to tresor_path(@abordage.tresor) }
        format.js
      end
    else

    end
  end

  def update
    authorize @abordage
    @abordage.tresor.vendu = true
    @abordage.tresor.save
    @abordage.pirate.abordages.each do |a|
      a.accepte = false
      a.save
    end
    @abordage.accepte = true
    @abordage.save
    redirect_to tresor_path(@abordage.tresor)
  end

  private

  def set_abordage
    @abordage = Abordage.find(params[:id])
  end

  def abordage_params
    params.require(:abordage).permit(:message, :quantite, :type_abordage_id)
  end
end

app/views/abordages/_form.html.erb
<%= simple_form_for([tresor, abordage], remote: true) do |f| %>
  <%= f.input :message, label: false, :input_html => { :class => 'to-reset' }  %>
   <div class="wide_buttons">
        <%= f.button :submit, "Envoyer", class: 'button yellow' %>
    </div>
<% end %>

app/views/abordages/_list.html.erb
<ul id="messages">
  <form>
  <% abordages.each do |abordage| %>
    <%= render "abordages/list_item", abordage: abordage, active: active %>
  <% end %>
  </form>
</ul>

app/views/abordages/_list_item.html.erb
<li class="message">
  <% if active && abordage.type_abordage && abordage.tresor.pirate == current_pirate %>
    <input type="radio" name="selector-mobile" id="abordage-item-<%= abordage.id %>">
    <label for="abordage-item-<%= abordage.id %>">
  <% else %>
    <label>
  <% end %>
    <div class="message-avatar">
      <% if abordage.pirate.photo? %>
        <%= cl_image_tag abordage.pirate.photo, class:'avatar', height: 60 %>
      <% else %>
        <%= image_tag 'pirate.svg', class:'avatar', height: 60 %>
      <% end %>
    </div>
    <div class="message-content">
      <h4><%= abordage.pirate.pseudo %>
        <% if abordage.type_abordage %>
          <em>propose</em> <%= pluralize abordage.quantite, abordage.type_abordage.nom %>
        <% end %>
      </h4>
      <p><%= abordage.message %></p>
    </div>
    <div class="message-type">
      <% if abordage.type_abordage %>
        <div class="message-choisir <%= abordage.type_abordage.emoji %>">
          <% if abordage.tresor.pirate == current_pirate && !abordage.tresor.vendu %>
            Choisir
          <% end %>
        </div>
      <% end %>
    </div>
  </label>
  <% if abordage.type_abordage && active && abordage.tresor.pirate == current_pirate %>
    <%= link_to "Choisir cette proposition", tresor_abordage_path(abordage.tresor, abordage), method: :patch, class:"btn-accept" %>
  <% end %>
</li>

app/views/abordages/_modal.html.erb
<div id="new-abordage-modal" class="gnd-modal modal-hidden">
  <div id="new-abordage-modal-background"></div>
  <div id="new-abordage-modal-error" class="hide-error">Choisis un type</div>
  <div class="content">
    <%= simple_form_for([tresor, abordage], remote: true) do |f| %>
    <div class="form-group radio_buttons optional init-class" id="abordage_type_abordage">
      <input type="hidden" name="abordage[type_abordage_id]" value="">
      <% TypeAbordage.all.each do |type| %>
      <span class="radio_choice_type">
        <label for="abordage_type_abordage_id_<%= type.id %>" class="radio" >
          <input class="radio_buttons optional to-reset-radio" type="radio" value="<%= type.id %>" name="abordage[type_abordage_id]" id="abordage_type_abordage_id_<%= type.id %>">
          <%= image_tag "#{type.emoji}.svg", class: "image-picker" %>
        </label>
      </span>
      <% end %>
    </div>
    <%= f.input :quantite, label: 'Combien ?', error: 'Indique la quantité', input_html: {value: 1, class: 'to-reset-int'} %>
    <%= f.input :message, placeholder: 'Message', label: false,  error: 'Et le message ?', :input_html => { :class => 'to-reset' } %>
    <div class="wide_buttons">
        <%= f.button :submit, "Envoyer", class: 'button yellow' %>
    </div>
    <% end %>
  </div>
</div>

app/views/abordages/_nav.html.erb
<div class="tabs">
  <div class="tab-item <%= 'active' if tab == 1 %>">
    <%= link_to pourparlers_traques_path do %>
    <h3><%= pluralize @abordages.count, "Traque" %></h3>
    <% end %>
  </div>
  <div class="tab-item <%= 'active' if tab == 2 %>">
    <%= link_to pourparlers_propositions_path do %>
    <h3><%= pluralize @tresors.count, "Trésor" %></h3>
    <% end %>
  </div>
</div>

app/views/abordages/_status.html.erb
<div class="status-container">
  <% c = Tresor.count_by_type(tresor) %>
  <% TypeAbordage.all.each do |type| %>
    <div class="status-item <%= type.emoji %>">
      <div class="count"><%= c[type.id] || 0 %></div>
    </div>
  <% end %>
</div>

app/views/abordages/create.js.erb
function refreshAbordageForm(){
  document.querySelectorAll(".to-reset").forEach((f) => f.value = "");
  if (document.getElementById("new-abordage-modal")){
      document.querySelector(".to-reset-int").value = 1;
    if (!document.getElementById("abordage_type_abordage").classList.contains("init-class")){
      document.getElementById("abordage_type_abordage").classList.add("init-class");
    }
    document.querySelectorAll(".to-reset-radio").forEach((r) => r.checked = false);
    if (document.getElementById("new-abordage-modal-error").classList.contains("show-error")){
      document.getElementById("new-abordage-modal-error").classList.remove("show-error");
      document.getElementById("new-abordage-modal-error").classList.add("hide-error");
    }
  }
}

function showErrorModal(){
  if (!document.getElementById("new-abordage-modal-error").classList.contains("show-error")){
    document.getElementById("new-abordage-modal-error").classList.add("hide-error");
    document.getElementById("new-abordage-modal-error").classList.add("show-error");
  }
}

function updateAbordageList(newContent){
  document.getElementById("messages").insertAdjacentHTML("beforeend", newContent);
}

function updateStatus(newContent){
  document.getElementById("status-update").innerHTML = newContent;
}

<% if @abordage.errors.any? %>
  refreshAbordageForm();
  showErrorModal();
<% else %>
  if (document.getElementById("new-abordage-modal")){
    if (!document.getElementById("new-abordage-modal").classList.contains("modal-hidden")){
      document.getElementById("new-abordage-modal").classList.add("modal-hidden");
    }
  }

  updateAbordageList( '<%= j render "abordages/list_item", abordage: @abordage, active: true %>' );
  updateStatus( '<%= j render "abordages/status", tresor: @tresor %>' );
  refreshAbordageForm();
<% end %>

app/views/abordages/propositions.html.erb
  <% content_for :meta_title, "Gold Next Door - La piraterie n'est jamais finie" %>
  <% content_for :meta_description, "Découvre des trésors cachés autour de toi jusqu'à aujourd'hui ! Dévoile les tiens pour savoir combien tu peux en tirer... Entre amis ou dans ton campus, qui sera le meilleur négociateur ?" %>
  <% content_for :meta_image, image_path('Gold_Next_Door.png') %>

<%= render "abordages/nav", tab: 2 %>
<ul class="pourparlers-list">
  <% @tresors.each do |tresor| %>
  <li class="pourparler">
    <%= cl_image_tag tresor.photo, height: 60, width: 60, crop: :fill %>
    <div class="content">
      <%= tresor.titre %><br><em><%= tresor.created_at.strftime("%d/%m/%Y") %></em>
    </div>
    <div class="abordage-status">
      <% if tresor.vendu %>
      Vendu
      <% else %>
      En cours
      <% end %>
    </div>
    <%= link_to "Voir", tresor_path(tresor), class:"link-tresor" %>
  </li>
  <%= render "abordages/status", tresor: tresor %>
  <% end %>
</ul>

app/views/abordages/traques.html.erb
<% content_for :meta_title, "Gold Next Door - La piraterie n'est jamais finie" %>
<% content_for :meta_description, "Découvre des trésors cachés autour de toi jusqu'à aujourd'hui ! Dévoile les tiens pour savoir combien tu peux en tirer... Entre amis ou dans ton campus, qui sera le meilleur négociateur ?" %>
<% content_for :meta_image, image_path('Gold_Next_Door.png') %>

<%= render "abordages/nav", tab: 1 %>
<ul class="pourparlers-list">
  <% @abordages.each do |abordage| %>
    <li class="pourparler">
      <% if abordage.tresor.prive && !abordage.tresor.vendu %>
      <%= image_tag 'lock2.png', height: 60, width: 60, crop: :fill %>
      <% else %>
      <%= cl_image_tag abordage.tresor.photo, height: 60, width: 60, crop: :fill %>
      <% end %>
      <div class="content">
        <% if abordage.tresor.prive && !abordage.tresor.vendu %>
          « <%= abordage.tresor.indice %> »
        <% else %>
          <%= abordage.tresor.titre %>
        <% end %>
         de <%= abordage.tresor.pirate.pseudo %>
          <br><%= image_tag "#{abordage.type_abordage.emoji}.svg", class:"mini-emoji" %><%= pluralize abordage.quantite, abordage.type_abordage.nom %>
        <br><em><%= abordage.created_at.strftime("%d/%m/%Y") %></em>
      </div>
      <div class="abordage-status">
        <% if abordage.tresor.vente == abordage %>
          Accepté
        <% elsif !abordage.tresor.vendu %>
          En cours
        <% else %>
          Refusé
        <% end %>
      </div>
      <%= link_to "Voir", tresor_path( abordage.tresor), class:"link-tresor" %>
    </li>
  <% end %>
</ul>